services:
  firebase:
    tty: true 
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 9005:9005 # firebase loginで使用
      - 9099:9099 # Firebase Authentication
      - 5001:5001 # Cloud Functions for Firebase
      - 8080:8080 # Cloud Firestore
      - 5000:5000 # Firebase Hosting
      - 9199:9199 # Cloud Storage
      - 4000:4000 # Emulator Suite UI
      - 4400:4400 # hub
      - 4500:4500 # logging
    command: firebase emulators:start
    working_dir: /opt/firebase